#!/usr/bin/env python3
"""Generate SUMO route file from YOLO tracking data.

Reads JSON tracking data generated by `process_video.py` for each
approach (North, South, East, West), extracts the exact arrival time
of each unique vehicle, and generates a deterministic SUMO `.rou.xml`
file using `<vehicle>` tags instead of random `<flow>` probabilities.

Usage:
    python scripts/generate_sumo_traffic.py \
        --north S01_c001_tracks.json \
        --south S01_c002_tracks.json \
        --east S01_c003_tracks.json \
        --west S01_c004_tracks.json \
        --output real_traffic.rou.xml
"""

import argparse
import json
import xml.etree.ElementTree as ET
from xml.dom import minidom


def parse_args():
    parser = argparse.ArgumentParser(description="Generate SUMO .rou.xml from YOLO tracking JSONs")
    parser.add_argument("--north", type=str, help="Path to North camera JSON")
    parser.add_argument("--south", type=str, help="Path to South camera JSON")
    parser.add_argument("--east", type=str, help="Path to East camera JSON")
    parser.add_argument("--west", type=str, help="Path to West camera JSON")
    parser.add_argument("--output", type=str, default="real_traffic.rou.xml", help="Output .rou.xml file")
    return parser.parse_args()


def extract_vehicles_from_json(json_path: str, route_id: str, prefix: str) -> list[dict]:
    """Extract first-seen time for each unique vehicle ID in a JSON file."""
    if not json_path:
        return []

    print(f"Loading {json_path} for route {route_id}...")
    try:
        with open(json_path, "r") as f:
            data = json.load(f)
    except Exception as e:
        print(f"  ERROR reading {json_path}: {e}")
        return []

    fps = data.get("metadata", {}).get("fps", 10.0)
    frames = data.get("frames", {})

    # We want the FIRST frame index where a vehicle ID appears
    first_seen = {}
    for frame_idx_str, detections in frames.items():
        frame_idx = int(frame_idx_str)
        for det in detections:
            vid = det["id"]
            if vid == -1:
                continue  # Skip untracked detections
            if vid not in first_seen:
                first_seen[vid] = {
                    "frame": frame_idx,
                    "class": det["class"],
                }

    vehicles = []
    for vid, info in first_seen.items():
        depart_time = info["frame"] / fps
        vehicles.append({
            "id": f"{prefix}_{vid}",
            "depart": round(depart_time, 2),
            "route": route_id,
            "vtype": "passenger",  # Simplify to passenger for now
        })

    print(f"  Extracted {len(vehicles)} unique vehicles.")
    return vehicles


def main():
    args = parse_args()

    all_vehicles = []
    all_vehicles.extend(extract_vehicles_from_json(args.north, "ns_through", "N"))
    all_vehicles.extend(extract_vehicles_from_json(args.south, "sn_through", "S"))
    all_vehicles.extend(extract_vehicles_from_json(args.east, "ew_through", "E"))
    all_vehicles.extend(extract_vehicles_from_json(args.west, "we_through", "W"))

    if not all_vehicles:
        print("ERROR: No vehicles extracted. Did you provide valid JSON files?")
        return

    # Sort globally by depart time, as required by SUMO
    all_vehicles.sort(key=lambda x: x["depart"])

    print(f"\nTotal unique vehicles across all cameras: {len(all_vehicles)}")

    # Create XML tree
    root = ET.Element("routes")
    root.set("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance")
    root.set("xsi:noNamespaceSchemaLocation", "http://sumo.dlr.de/xsd/routes_file.xsd")

    # Add vType
    vtype = ET.SubElement(root, "vType")
    vtype.set("id", "passenger")
    vtype.set("accel", "2.6")
    vtype.set("decel", "4.5")
    vtype.set("sigma", "0.5")
    vtype.set("length", "5.0")
    vtype.set("minGap", "2.5")
    vtype.set("maxSpeed", "13.89")
    vtype.set("guiShape", "passenger")

    # Add Routes
    ET.SubElement(root, "route", id="ns_through", edges="north_in south_out")
    ET.SubElement(root, "route", id="sn_through", edges="south_in north_out")
    ET.SubElement(root, "route", id="ew_through", edges="east_in west_out")
    ET.SubElement(root, "route", id="we_through", edges="west_in east_out")

    # Add Vehicles
    for v in all_vehicles:
        veh = ET.SubElement(root, "vehicle")
        veh.set("id", v["id"])
        veh.set("depart", str(v["depart"]))
        veh.set("route", v["route"])
        veh.set("type", v["vtype"])
        veh.set("departLane", "best")
        veh.set("departSpeed", "max")

    # Write to file
    xml_str = ET.tostring(root, encoding="utf-8")
    parsed = minidom.parseString(xml_str)
    pretty_xml = parsed.toprettyxml(indent="    ")

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(pretty_xml)

    print(f"✅ Generated SUMO route file: {args.output}")


if __name__ == "__main__":
    main()
