# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgraph.proto\x12\x08semaforo\"/\n\x08GeoPoint\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"\x8b\x01\n\x0cIntersection\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12$\n\x08location\x18\x03 \x01(\x0b\x32\x12.semaforo.GeoPoint\x12\x16\n\x0enum_approaches\x18\x04 \x01(\r\x12\x12\n\nhas_signal\x18\x05 \x01(\x08\x12\x0f\n\x07zone_id\x18\x06 \x01(\t\"\xa7\x01\n\x04Road\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tsource_id\x18\x03 \x01(\t\x12\x11\n\ttarget_id\x18\x04 \x01(\t\x12\x12\n\ndistance_m\x18\x05 \x01(\x02\x12\x17\n\x0fspeed_limit_kmh\x18\x06 \x01(\x02\x12\r\n\x05lanes\x18\x07 \x01(\r\x12\x0f\n\x07one_way\x18\x08 \x01(\x08\x12\x12\n\nroad_class\x18\t \x01(\t\"\xa6\x01\n\x0fNetworkTopology\x12\x12\n\nnetwork_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12-\n\rintersections\x18\x03 \x03(\x0b\x32\x16.semaforo.Intersection\x12\x1d\n\x05roads\x18\x04 \x03(\x0b\x32\x0e.semaforo.Road\x12\x0f\n\x07version\x18\x05 \x01(\r\x12\x12\n\nupdated_at\x18\x06 \x01(\x04\x42\x41\n\x1b\x63om.becashub.semaforo.protoZ\"github.com/becashub/semaforo/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.becashub.semaforo.protoZ\"github.com/becashub/semaforo/proto'
  _globals['_GEOPOINT']._serialized_start=25
  _globals['_GEOPOINT']._serialized_end=72
  _globals['_INTERSECTION']._serialized_start=75
  _globals['_INTERSECTION']._serialized_end=214
  _globals['_ROAD']._serialized_start=217
  _globals['_ROAD']._serialized_end=384
  _globals['_NETWORKTOPOLOGY']._serialized_start=387
  _globals['_NETWORKTOPOLOGY']._serialized_end=553
# @@protoc_insertion_point(module_scope)
