# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timing_plan.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'timing_plan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11timing_plan.proto\x12\x08semaforo\"g\n\x0fPhaseDefinition\x12\x10\n\x08phase_id\x18\x01 \x01(\t\x12\x12\n\nduration_s\x18\x02 \x01(\r\x12\x16\n\x0emin_duration_s\x18\x03 \x01(\r\x12\x16\n\x0emax_duration_s\x18\x04 \x01(\r\"\x82\x01\n\x12IntersectionOffset\x12\x17\n\x0fintersection_id\x18\x01 \x01(\t\x12\x10\n\x08offset_s\x18\x02 \x01(\r\x12\x16\n\x0e\x63ycle_length_s\x18\x03 \x01(\r\x12)\n\x06phases\x18\x04 \x03(\x0b\x32\x19.semaforo.PhaseDefinition\"|\n\x08\x43orridor\x12\x13\n\x0b\x63orridor_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x18\n\x10\x64\x65sign_speed_kmh\x18\x03 \x01(\x02\x12\x33\n\rintersections\x18\x04 \x03(\x0b\x32\x1c.semaforo.IntersectionOffset\"\xa5\x01\n\nTimingPlan\x12\x0f\n\x07plan_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x0f\n\x07zone_id\x18\x03 \x01(\t\x12\x16\n\x0e\x63ycle_length_s\x18\x04 \x01(\r\x12%\n\tcorridors\x18\x05 \x03(\x0b\x32\x12.semaforo.Corridor\x12\x13\n\x0bvalid_for_s\x18\x06 \x01(\r\x12\x0e\n\x06source\x18\x07 \x01(\tBA\n\x1b\x63om.becashub.semaforo.protoZ\"github.com/becashub/semaforo/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timing_plan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.becashub.semaforo.protoZ\"github.com/becashub/semaforo/proto'
  _globals['_PHASEDEFINITION']._serialized_start=31
  _globals['_PHASEDEFINITION']._serialized_end=134
  _globals['_INTERSECTIONOFFSET']._serialized_start=137
  _globals['_INTERSECTIONOFFSET']._serialized_end=267
  _globals['_CORRIDOR']._serialized_start=269
  _globals['_CORRIDOR']._serialized_end=393
  _globals['_TIMINGPLAN']._serialized_start=396
  _globals['_TIMINGPLAN']._serialized_end=561
# @@protoc_insertion_point(module_scope)
